name: CI/CD Pipeline

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'

        - name: Install dependencies
          run: |
            pip install -r requirements.txt

        - name: Run tests
          run: |
            python -m pytest

        - name: Build Docker image
          run: |
            docker build -t ai-notes-app .

        - name: Test Docker container
          run: |
            docker run -d -p 5000:5000 --name test-container ai-notes-app
            sleep 8
            curl -f hhtp://localhost:5000/api/health || exit 1
            docker stop test-container
            docker rm test-container